

-- ============================================================================
-- نظام الأدوار والصلاحيات - Marketna
-- مدمج مع نظام البروفايل الحالي
-- ============================================================================

-- ============================================================================
-- 1. تحصين دالة إنشاء البروفايل (مهم جداً!)
-- ============================================================================
create or replace function public.handle_new_user()
returns trigger as $$
declare
  customer_role_id bigint;
begin
  -- أ) إنشاء البروفايل (محصن ضد الأخطاء)
  begin
    insert into public.profiles (
      id,
      first_name,
      last_name,
      email,
      phone_number,
      gender,
      profile_image
    )
    values (
      new.id,
      COALESCE(new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'full_name', 'مستخدم جديد'),
      new.raw_user_meta_data->>'last_name',
      new.email,
      new.phone,
      COALESCE(new.raw_user_meta_data->>'gender', 'other'),
      new.raw_user_meta_data->>'avatar_url'
    )
    ON CONFLICT (id) DO NOTHING;
  exception when others then
    -- تجاهل أي خطأ في إنشاء البروفايل
    null;
  end;

  -- ب) منح دور customer تلقائياً
  begin
    select id into customer_role_id 
    from public.roles 
    where name = 'customer' 
    limit 1;
    
    if customer_role_id is not null then
      insert into public.user_roles (user_id, role_id)
      values (new.id, customer_role_id)
      ON CONFLICT (user_id, role_id) DO NOTHING;
    end if;
  exception when others then
    -- تجاهل أي خطأ في منح الدور
    null;
  end;

  return new;
end;
$$ language plpgsql security definer set search_path = public;

-- ============================================================================
-- 2. جدول الأدوار (مع الصلاحيات كـ JSONB)
-- ============================================================================
create table if not exists public.roles (
  id          bigint generated by default as identity primary key,
  name        text unique not null,
  description text,
  permissions jsonb not null default '[]'::jsonb,
  created_at  timestamptz default timezone('utc'::text, now()) not null
);
comment on table public.roles is 'Application roles with permissions stored as JSONB.';

-- ============================================================================
-- 3. جدول ربط المستخدمين بالأدوار
-- ============================================================================
create table if not exists public.user_roles (
  id         bigint generated by default as identity primary key,
  user_id    uuid references auth.users(id) on delete cascade not null,
  role_id    bigint references public.roles(id) on delete cascade not null,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  unique (user_id, role_id)
);
comment on table public.user_roles is 'Maps users to their roles.';

-- ============================================================================
-- 4. البيانات الافتراضية
-- ============================================================================
insert into public.roles (name, description, permissions) values
  ('admin', 'صلاحيات كاملة', '["manage_all", "manage_users", "manage_products", "manage_orders", "view_all"]'::jsonb),
  ('customer', 'عميل عادي', '["view_products", "manage_own_orders", "view_own_profile"]'::jsonb)
ON CONFLICT (name) DO UPDATE SET 
  description = EXCLUDED.description,
  permissions = EXCLUDED.permissions;

-- ============================================================================
-- 5. تفعيل RLS
-- ============================================================================
alter table public.roles enable row level security;
alter table public.user_roles enable row level security;

-- ============================================================================
-- 6. سياسات RLS
-- ============================================================================
drop policy if exists "Anyone can read roles" on public.roles;
create policy "Anyone can read roles" on public.roles for select using (true);

drop policy if exists "Users view own roles" on public.user_roles;
create policy "Users view own roles" on public.user_roles for select
using (
  user_id = auth.uid() OR 
  exists (
    select 1 from public.user_roles ur
    join public.roles r on ur.role_id = r.id
    where ur.user_id = auth.uid() and r.name = 'admin'
  )
);

drop policy if exists "Only admins manage roles" on public.user_roles;
create policy "Only admins manage roles" on public.user_roles for all
using (
  exists (
    select 1 from public.user_roles ur
    join public.roles r on ur.role_id = r.id
    where ur.user_id = auth.uid() and r.name = 'admin'
  )
);

-- ============================================================================
-- 7. Trigger لتحديث JWT عند تغيير الدور
-- ============================================================================
create or replace function public.handle_role_change()
returns trigger as $$
declare
  role_name text;
  role_perms jsonb;
begin
  select name, permissions into role_name, role_perms 
  from public.roles 
  where id = NEW.role_id;
  
  update auth.users
  set raw_app_meta_data = coalesce(raw_app_meta_data, '{}'::jsonb) ||
    jsonb_build_object(
      'role', role_name, 
      'permissions', coalesce(role_perms, '[]'::jsonb)
    )
  where id = NEW.user_id;
  
  return NEW;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists on_role_change on public.user_roles;
create trigger on_role_change 
  after insert or update on public.user_roles
  for each row 
  execute function public.handle_role_change();

-- ============================================================================
-- 8. تحديث Trigger إنشاء المستخدم ليشمل الأدوار
-- ============================================================================
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row 
  execute function public.handle_new_user();

-- ============================================================================
-- 9. منح الصلاحيات
-- ============================================================================
grant select on public.roles to authenticated, anon;
grant select, insert, update, delete on public.user_roles to authenticated;

-- ============================================================================
-- ✅ تم بناء نظام الأدوار والصلاحيات بنجاح!
-- ============================================================================






-- التحقق من إنشاء البروفايل والدور والصلاحيات تلقائياً
SELECT 
  u.email,
  u.raw_app_meta_data,
  p.first_name,
  r.name AS role_name,
  r.permissions
FROM auth.users u
LEFT JOIN public.profiles p ON u.id = p.id
LEFT JOIN public.user_roles ur ON u.id = ur.user_id
LEFT JOIN public.roles r ON ur.role_id = r.id
WHERE u.email = 'm.thelord963@gmail.com';



-- 1. حذف الدور الحالي (customer)
DELETE FROM public.user_roles 
WHERE user_id = (SELECT id FROM auth.users WHERE email = 'm.thelord963@gmail.com');

-- 2. منح دور admin
INSERT INTO public.user_roles (user_id, role_id)
VALUES (
  (SELECT id FROM auth.users WHERE email = 'm.thelord963@gmail.com'),
  (SELECT id FROM public.roles WHERE name = 'admin')
);









